let s_descr = Unix.socket Unix.PF_INET Unix.SOCK_DGRAM 0 ;; (* create socket for DATAGRAM *)
let s_ServerString = "127.0.0.1" ;; (* string for server address *)
let s_IAddress = Unix.inet_addr_of_string s_string ;; (* internet address for server *)
let s_Port = 12345 ;; (* port for server *)
let s_addr = Unix.ADDR_INET(s_IAddress , s_Port) ;; (* ? *)
Unix.connect s_descr s_addr ;; (* connect to server *)
(* TODO create datagram *)
(* TODO write datagram to socket *)
print_endline "Hello World!" ;; (* test if we get to this line *)
Unix.close s_descr ;; (* close socket *)
